ROI_MAPPING = {
    307: "Total Cerebral Cortex SUVR",
    407: "Left Cerebral Cortex SUVR",
    507: "Right Cerebral Cortex SUVR",
    301: "Total Frontal Cortex SUVR",
    401: "Left Frontal Cortex SUVR",
    501: "Right Frontal Cortex SUVR",
    16: "Total Caudal Middle Frontal SUVR",
    116: "Left Caudal Middle Frontal SUVR",
    216: "Right Caudal Middle Frontal SUVR",
    24: "Total Lateral Orbitofrontal SUVR",
    124: "Left Lateral Orbitofrontal SUVR",
    224: "Right Lateral Orbitofrontal SUVR",
    26: "Total Medial Orbitofrontal SUVR",
    126: "Left Medial Orbitofrontal SUVR",
    226: "Right Medial Orbitofrontal SUVR",
    30: "Total Pars Opercularis SUVR",
    130: "Left Pars Opercularis SUVR",
    230: "Right Pars Opercularis SUVR",
    31: "Total Pars Orbitalis SUVR",
    131: "Left Pars Orbitalis SUVR",
    231: "Right Pars Orbitalis SUVR",
    32: "Total Pars Triangularis SUVR",
    132: "Left Pars Triangularis SUVR",
    232: "Right Pars Triangularis SUVR",
    39: "Total Rostral Middle Frontal SUVR",
    139: "Left Rostral Middle Frontal SUVR",
    239: "Right Rostral Middle Frontal SUVR",
    40: "Total Superior Frontal SUVR",
    140: "Left Superior Frontal SUVR",
    240: "Right Superior Frontal SUVR",
    44: "Total Frontal Pole SUVR",
    144: "Left Frontal Pole SUVR",
    244: "Right Frontal Pole SUVR",
    36: "Total Precentral SUVR",
    136: "Left Precentral SUVR",
    236: "Right Precentral SUVR",
    29: "Total Paracentral SUVR",
    129: "Left Paracentral SUVR",
    229: "Right Paracentral SUVR",
    303: "Total Parietal Cortex SUVR",
    403: "Left Parietal Cortex SUVR",
    503: "Right Parietal Cortex SUVR",
    20: "Total Inferior Parietal SUVR",
    120: "Left Inferior Parietal SUVR",
    220: "Right Inferior Parietal SUVR",
    37: "Total Precuneus SUVR",
    137: "Left Precuneus SUVR",
    237: "Right Precuneus SUVR",
    41: "Total Superior Parietal SUVR",
    141: "Left Superior Parietal SUVR",
    241: "Right Superior Parietal SUVR",
    43: "Total Supramarginal SUVR",
    143: "Left Supramarginal SUVR",
    243: "Right Supramarginal SUVR",
    34: "Total Postcentral SUVR",
    134: "Left Postcentral SUVR",
    234: "Right Postcentral SUVR",
    302: "Total Temporal Cortex SUVR",
    402: "Left Temporal Cortex SUVR",
    502: "Right Temporal Cortex SUVR",
    27: "Total Middle Temporal SUVR",
    127: "Left Middle Temporal SUVR",
    227: "Right Middle Temporal SUVR",
    42: "Total Superior Temporal SUVR",
    142: "Left Superior Temporal SUVR",
    242: "Right Superior Temporal SUVR",
    14: "Total Posterior Transverse Temporal SUVR",
    114: "Left Posterior Transverse Temporal SUVR",
    214: "Right Posterior Transverse Temporal SUVR",
    18: "Total Entorhinal SUVR",
    118: "Left Entorhinal SUVR",
    218: "Right Entorhinal SUVR",
    19: "Total Fusiform SUVR",
    119: "Left Fusiform SUVR",
    219: "Right Fusiform SUVR",
    21: "Total Inferior Temporal SUVR",
    121: "Left Inferior Temporal SUVR",
    221: "Right Inferior Temporal SUVR",
    28: "Total Parahippocampal SUVR",
    128: "Left Parahippocampal SUVR",
    228: "Right Parahippocampal SUVR",
    45: "Total Temporal Pole SUVR",
    145: "Left Temporal Pole SUVR",
    245: "Right Temporal Pole SUVR",
    46: "Total Transverse Temporal SUVR",
    146: "Left Transverse Temporal SUVR",
    246: "Right Transverse Temporal SUVR",
    304: "Total Occipital Cortex SUVR",
    404: "Left Occipital Cortex SUVR",
    504: "Right Occipital Cortex SUVR",
    17: "Total Cuneus SUVR",
    117: "Left Cuneus SUVR",
    217: "Right Cuneus SUVR",
    23: "Total Lateral Occipital SUVR",
    123: "Left Lateral Occipital SUVR",
    223: "Right Lateral Occipital SUVR",
    25: "Total Lingual SUVR",
    125: "Left Lingual SUVR",
    225: "Right Lingual SUVR",
    33: "Total Pericalcarine SUVR",
    133: "Left Pericalcarine SUVR",
    233: "Right Pericalcarine SUVR",
    305: "Total Cingulate Cortex SUVR",
    405: "Left Cingulate Cortex SUVR",
    505: "Right Cingulate Cortex SUVR",
    15: "Total Caudal Anterior Cingulate SUVR",
    115: "Left Caudal Anterior Cingulate SUVR",
    215: "Right Caudal Anterior Cingulate SUVR",
    22: "Total Isthmus of Cingulate SUVR",
    122: "Left Isthmus of Cingulate SUVR",
    222: "Right Isthmus of Cingulate SUVR",
    35: "Total Posterior Cingulate SUVR",
    135: "Left Posterior Cingulate SUVR",
    235: "Right Posterior Cingulate SUVR",
    38: "Total Rostral Anterior Cingulate SUVR",
    138: "Left Rostral Anterior Cingulate SUVR",
    238: "Right Rostral Anterior Cingulate SUVR",
    316: "Total Subcortical Regions SUVR",
    416: "Left Subcortical Regions SUVR",
    516: "Right Subcortical Regions SUVR",
    7: "Total Caudate SUVR",
    107: "Left Caudate SUVR",
    207: "Right Caudate SUVR",
    8: "Total Putamen SUVR",
    108: "Left Putamen SUVR",
    208: "Right Putamen SUVR",
    6: "Total Thalamus SUVR",
    106: "Left Thalamus SUVR",
    206: "Right Thalamus SUVR",
    9: "Total Pallidum SUVR",
    109: "Left Pallidum SUVR",
    209: "Right Pallidum SUVR",
    10: "Total Hippocampus SUVR",
    110: "Left Hippocampus SUVR",
    210: "Right Hippocampus SUVR",
    11: "Total Amygdala SUVR",
    111: "Left Amygdala SUVR",
    211: "Right Amygdala SUVR",
    12: "Total Accumbens SUVR",
    112: "Left Accumbens SUVR",
    212: "Right Accumbens SUVR",
    306: "Total Cerebellum SUVR",
    406: "Left Cerebellum SUVR",
    506: "Right Cerebellum SUVR",
    4: "Total Cerebellum White Matter SUVR",
    104: "Left Cerebellum White Matter SUVR",
    204: "Right Cerebellum White Matter SUVR",
    5: "Total Cerebellum Grey Matter SUVR",
    105: "Left Cerebellum Grey Matter SUVR",
    205: "Right Cerebellum Grey Matter SUVR",
    97: "Total Brainstem SUVR",
    94: "Total Pons SUVR",
    47: "Total Insula Cortex SUVR",
    147: "Left Insula Cortex SUVR",
    247: "Right Insula Cortex SUVR",
    13: "Total Ventral Diencephalon SUVR",
    113: "Left Ventral Diencephalon SUVR",
    213: "Right Ventral Diencephalon SUVR",
    98: "Total Corpus Callosum SUVR",
    1010: "Total Braak ROI Global SUVR",
    1110: "Left Braak ROI Global SUVR",
    1210: "Right Braak ROI Global SUVR",
    1007: "Total Braak I/II ROI SUVR",
    1107: "Left Braak I/II ROI SUVR",
    1207: "Right Braak I/II ROI SUVR",
    1001: "Total Braak I ROI SUVR",
    1101: "Left Braak I ROI SUVR",
    1201: "Right Braak I ROI SUVR",
    1002: "Total Braak II ROI SUVR",
    1102: "Left Braak II ROI SUVR",
    1202: "Right Braak II ROI SUVR",
    1008: "Total Braak III/IV ROI SUVR",
    1108: "Left Braak III/IV ROI SUVR",
    1208: "Right Braak III/IV ROI SUVR",
    1003: "Total Braak III ROI SUVR",
    1103: "Left Braak III ROI SUVR",
    1203: "Right Braak III ROI SUVR",
    1004: "Total Braak IV ROI SUVR",
    1104: "Left Braak IV ROI SUVR",
    1204: "Right Braak IV ROI SUVR",
    1009: "Total Braak V/VI ROI SUVR",
    1109: "Left Braak V/VI ROI SUVR",
    1209: "Right Braak V/VI ROI SUVR",
    1005: "Total Braak V ROI SUVR",
    1105: "Left Braak V ROI SUVR",
    1205: "Right Braak V ROI SUVR",
    1006: "Total Braak VI ROI SUVR",
    1106: "Left Braak VI ROI SUVR",
    1206: "Right Braak VI ROI SUVR",
    1011: "Total A Priori ROI SUVR",
    1111: "Left A Priori ROI SUVR",
    1211: "Right A Priori ROI SUVR",
    317: "Total Regions of Interest for Amyloid PET SUVR",
    417: "Left Regions of Interest for Amyloid PET SUVR",
    517: "Right Regions of Interest for Amyloid PET SUVR",
    315: "Total Striatum SUVR",
    415: "Left Striatum SUVR",
    515: "Right Striatum SUVR",
    52: "Total Anterior Caudate SUVR",
    152: "Left Anterior Caudate SUVR",
    252: "Right Anterior Caudate SUVR",
    51: "Total Posterior Caudate SUVR",
    151: "Left Posterior Caudate SUVR",
    251: "Right Posterior Caudate SUVR",
    55: "Total Anterior Putamen SUVR",
    155: "Left Anterior Putamen SUVR",
    255: "Right Anterior Putamen SUVR",
    54: "Total Posterior Putamen SUVR",
    154: "Left Posterior Putamen SUVR",
    254: "Right Posterior Putamen SUVR",
    53: "Total Ventral Putamen SUVR",
    153: "Left Ventral Putamen SUVR",
    253: "Right Ventral Putamen SUVR",
    50: "Total Ventral Striatum SUVR",
    150: "Left Ventral Striatum SUVR",
    250: "Right Ventral Striatum SUVR",
    311: "Total Frontal Target Region SUVR",
    411: "Left Frontal Target Region SUVR",
    511: "Right Frontal Target Region SUVR",
    313: "Total Lateral Parietal Target Region SUVR",
    413: "Left Lateral Parietal Target Region SUVR",
    513: "Right Lateral Parietal Target Region SUVR",
    314: "Total Lateral Temporal Target Region SUVR",
    414: "Left Lateral Temporal Target Region SUVR",
    514: "Right Lateral Temporal Target Region SUVR"
}


