mapping_dict = {
    ('Cerebral White Matter WMH_Volume', 900): 'Cerebral White Matter WMH',
    ('Deep White Matter WMH_Volume', 901): 'Deep White Matter WMH',
    ('Periventricular White Matter WMH_Volume', 902): 'Periventricular White Matter WMH',
    ('Cerebral White Matter WMH_% of WM', 900): 'Cerebral White Matter WMH',
    ('Deep White Matter WMH_% of WM', 901): 'Deep White Matter WMH',
    ('Periventricular White Matter WMH_% of WM', 902): 'Periventricular White Matter WMH',
    ('Cerebral White Matter_Fazekas Scale', 900): 'Cerebral White Matter',
    ('Juxtacortical_Lesion Count', 903): 'Juxtacortical',
    ('Periventricular White Matter_Lesion Count', 902): 'Periventricular White Matter',
    ('Deep White Matter_Lesion Count', 901): 'Deep White Matter',
    ('Infratentorial_Lesion Count', 904): 'Infratentorial',
    ('Juxtacortical_Lesion Volume', 903): 'Juxtacortical',
    ('Periventricular White Matter_Lesion Volume', 902): 'Periventricular White Matter',
    ('Deep White Matter_Lesion Volume', 901): 'Deep White Matter',
    ('Infratentorial_Lesion Volume', 904): 'Infratentorial',
    ('Juxtacortical_% of WM', 903): 'Juxtacortical',
    ('Periventricular White Matter_% of WM', 902): 'Periventricular White Matter',
    ('Deep White Matter_% of WM', 901): 'Deep White Matter',
    ('Infratentorial_% of WM', 904): 'Infratentorial',
    ('Whole Brain_Region Volume', 323): 'Whole Brain',
    ('Cerebral Grey Matter_Region Volume', 2): 'Cerebral Grey Matter',
    ('Cerebral White Matter_Region Volume', 1): 'Cerebral White Matter',
    ('Brainstem_Region Volume', 97): 'Brainstem',
    ('Cerebellum_Region Volume', 306): 'Cerebellum',
    ('Lateral Ventricles_Region Volume', 307): 'Lateral Ventricles',
    ('Third Ventricle_Region Volume', 95): 'Third Ventricle',
    ('Fourth Ventricle_Region Volume', 96): 'Fourth Ventricle',
}