mapping_dict = {
    ('WMH_VOLUME', 900): 'Cerebral White Matter_Volume',
    ('WMH_VOLUME', 901): 'Deep White Matter_Volume',
    ('WMH_VOLUME', 902): 'Periventricular White Matter_Volume',
    ('WMH_PERCENT_OF_WM', 900): 'Cerebral White Matter_% of WM',
    ('WMH_PERCENT_OF_WM', 901): 'Deep White Matter_% of WM1',
    ('WMH_PERCENT_OF_WM', 902): 'Periventricular White Matter_% of WM1',
    ('WMH_FAZEKAS_SCALE', 900): 'Cerebral White Matter_Fazekas Scale',
    ('LESION_COUNT', 903): 'Juxtacortical_Lesion Count',
    ('LESION_COUNT', 902): 'Periventricular White Matter_Lesion Count',
    ('LESION_COUNT', 901): 'Deep White Matter_Lesion Count',
    ('LESION_COUNT', 904): 'Infratentorial_Lesion Count',
    ('LESION_VOLUME', 903): 'Juxtacortical_Lesion Volume',
    ('LESION_VOLUME', 902): 'Periventricular White Matter_Lesion Volume',
    ('LESION_VOLUME', 901): 'Deep White Matter_Lesion Volume',
    ('LESION_VOLUME', 904): 'Infratentorial_Lesion Volume',
    ('LESION_VOLUME_PERCENT_OF_WM', 903): 'Juxtacortical_% of WM',
    ('LESION_VOLUME_PERCENT_OF_WM', 902): 'Periventricular White Matter_% of WM',
    ('LESION_VOLUME_PERCENT_OF_WM', 901): 'Deep White Matter_% of WM',
    ('LESION_VOLUME_PERCENT_OF_WM', 904): 'Infratentorial_% of WM',
    ('FLAIR_CURRENT_VOLUME', 323): 'Whole Brain_Region Volume',
    ('FLAIR_CURRENT_VOLUME', 2): 'Cerebral Grey Matter_Region Volume',
    ('FLAIR_CURRENT_VOLUME', 1): 'Cerebral White Matter_Region Volume',
    ('FLAIR_CURRENT_VOLUME', 97): 'Brainstem_Region Volume',
    ('FLAIR_CURRENT_VOLUME', 306): 'Cerebellum_Region Volume',
    ('FLAIR_CURRENT_VOLUME', 307): 'Lateral Ventricles_Region Volume',
    ('FLAIR_CURRENT_VOLUME', 95): 'Third Ventricle_Region Volume',
    ('FLAIR_CURRENT_VOLUME', 96): 'Fourth Ventricle_Region Volume',
}